version: 0.0
os: linux
files:
  - source: /
    destination: /application/
hooks:
  BeforeInstall:
    - location: code_deploy_scripts/install_dependencies.sh
      timeout: 300
      runas: root
  Install: 
    - location: code_deploy_scripts/install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: code_deploy_scripts/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: code_deploy_scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: code_deploy_scripts/stop_server.sh
      timeout: 300
      runas: root