version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/node-application/video-recording-with-webrtc/
hooks:
  BeforeInstall:
    - location: code_deploy_scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  Install: 
    - location: code_deploy_scripts/install.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: code_deploy_scripts/after_install.sh
      timeout: 300
      runas: ec2-user
  ValidateService: 
    - location: code_deploy_scripts/update_environment_variables.sh
      timeout: 300
      runas: ec2-user    
  ApplicationStart:
    - location: code_deploy_scripts/start_server.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: code_deploy_scripts/stop_server.sh
      timeout: 300
      runas: ec2-user