version: 2
jobs:
  build:
    docker:
      - image: node:6.11.2
      - image: redis:3.2.4
    steps:
      - checkout
      - run: 
          name: Add application dependencies
          command: |
            npm install -g bower
            npm install pm2 -g 

      # Install & Cache 
      # NPM vendors
      - restore_cache: 
          keys: 
            - npm-cache-1-{{ checksum "package.json" }}
            - npm-cache-1       
      - run: 
          name: Install Node
          command: |
            npm install     
      - save_cache: 
          key: npm-cache-1-{{ checksum "package.json" }}
          paths: 
            - node_modules

      # Install & Cache 
      # bower vendors            
      - restore_cache: 
          keys: 
            - bower-cache-1-{{ checksum "bower.json" }}
            - bower-cache         
      - run: 
          name: Install Bower
          command: |
            bower install    
      - save_cache: 
          key: bower-cache-1-{{ checksum "bower.json" }}
          paths: 
            - public/bower_components
      # Start NPM 
      - run:
          name: Start Application
          command: | 
            npm start