version: 2
jobs:
  build:
    branches: #SET the only branches that are allowed for build
      only:
        - development
    docker:
      - image: node:6.11.2 #primary container
        environment: 
          VT_REDIS_HOST: 127.0.0.1
          VT_REDIS_PORT: 6379
      - image: redis:3.2.4 #add redis image
    steps:
      - checkout
      - run: 
          name: Add application dependencies
          command: |
            npm install -g bower
            npm install pm2 -g 

      # Install & Cache 
      # NPM vendors
      - restore_cache: 
          keys: 
            - npm-cache-1-{{ checksum "package.json" }}
            - npm-cache-1       
      - run: 
          name: Install Node
          command: |
            npm install     
      - save_cache: 
          key: npm-cache-1-{{ checksum "package.json" }}
          paths: 
            - node_modules

      # Install & Cache 
      # bower vendors            
      - restore_cache: 
          keys: 
            - bower-cache-1-{{ checksum "bower.json" }}
            - bower-cache         
      - run: 
          name: Install Bower
          command: |
            bower install    
      - save_cache: 
          key: bower-cache-1-{{ checksum "bower.json" }}
          paths: 
            - public/bower_components

      #Test Application
      # - run:
      #     name: Test Application
      #     command: | 
      #       npm test 
      # Check Health
      # - run: 
      #     name: Check Health
      #     command: |
      #       curl --connect-timeout 2.37 --max-time 5.00 http://127.0.0.1:8081/api/healthcheck 

  test: 
    docker:
      - image: node:6.11.2 #primary container
        environment: 
          VT_REDIS_HOST: 127.0.0.1
          VT_REDIS_PORT: 6379
      - image: redis:3.2.4 #add redis image     
    steps: 
      - checkout
      - run: 
          name: Test
          command: npm test
      - store_artifacts: 
          path: test-results.xml
          prefix: tests