version: 2
jobs:
  build:
    docker:
      - image: node:6.11.2
    steps:
      - checkout
      - run: 
          name: Add application dependencies
          command: |
            npm install -g bower
      - run: 
          name: Install Node
          command: |
            npm install      
      - run: 
          name: Install Bower
          command: |
            bower install               