version: 2
jobs:
  build:
    docker:
      - image: node:6.11.2
    steps:
      - checkout
      - run: 
          name: Add application dependencies
          command: |
            npm install -g bower

      # Install & Cache 
      # NPM vendors
      - restore_cache: 
          keys: 
            - npm-cache-{{ checksum "package.json" }}
            - npm-cache       
      - run: 
          name: Install Node
          command: |
            npm install     
      - save_cache: 
          key: npm-cache-{{ checksum "package.json" }}
          paths: 
            - node_modules

      # Install & Cache 
      # bower vendors            
      - restore_cache: 
          keys: 
            - bower-cache-{{ checksum "bower.json" }}
            - bower-cache         
      - run: 
          name: Install Bower
          command: |
            bower install    
      - save_cache: 
          key: bower-cache-{{ checksum "bower.json" }}
          paths: 
            - public/bower_components
           