version: 0.2
            
phases:
  install:
    commands:
      - echo Entered the install phase...
      - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
      - apt-get install -y nodejs 
      - npm install -g bower
  pre_build:
    commands:
      - echo install dependencies
      - npm install
      - bower install
      - echo add redis
      - docker run --name packt-redis -p 16379:6379 -d redis:3.2.4 
  build:
    commands:
      - npm test
  post_build:
    commands:
      - npm start